# Generated by Django 5.0.2 on 2024-02-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(default="email", max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EXECUTIVE", "Executive"),
                    ("UNIVERSITY_STUDENT", "University Student"),
                    ("SECONDARY_STUDENT", "Secondary Student"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
