# Generated by Django 5.0.2 on 2024-02-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_userprofile_phone_number_alter_userprofile_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.URLField(blank=True, null=True),
        ),
    ]
