# Generated by Django 5.0.2 on 2024-02-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="city_of_residence",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
