# Generated by Django 5.0.2 on 2024-02-28 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_city_of_residence"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("membership_id", models.CharField(max_length=255, unique=True)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("bio", models.TextField()),
                (
                    "city_of_residence",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("profile_picture", models.URLField()),
                ("branch", models.CharField(max_length=255)),
                ("year_of_admission", models.DateField()),
                ("year_of_graduation", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("faculty", models.CharField(blank=True, max_length=255, null=True)),
                ("department", models.CharField(blank=True, max_length=255, null=True)),
                ("level", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "school_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "school_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "student_class",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "ordering": ["membership_id"],
            },
        ),
        migrations.RemoveField(
            model_name="baseuserprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="universitystudentprofile",
            name="baseuserprofile_ptr",
        ),
        migrations.RemoveField(
            model_name="executiveprofile",
            name="universitystudentprofile_ptr",
        ),
        migrations.RemoveField(
            model_name="user",
            name="age",
        ),
        migrations.RemoveField(
            model_name="user",
            name="city_of_residence",
        ),
        migrations.DeleteModel(
            name="SecondaryStudentProfile",
        ),
        migrations.DeleteModel(
            name="BaseUserProfile",
        ),
        migrations.DeleteModel(
            name="ExecutiveProfile",
        ),
        migrations.DeleteModel(
            name="UniversityStudentProfile",
        ),
    ]
